Add support for retrieving s3 credentials from AWS credentials file
buchgr/bazel-remote pull request #492
Opened 2021-10-27 22:15 UTC by justfalter

This pull request adds support for retrieving credentials from AWS credentials files (often used by [aws-cli](https://aws.amazon.com/cli/)).

As a regular user of the aws-cli, this change allows bazel-remote to leverage credentials I've already got (access key, secret key, session tokens, etc) without having to goof around with anything else. Note, this is something that minio-go already supports, I am just wiring things up.

I took the opportunity move the credentials parsing out to a `GetCredentials` function. I felt uncomfortable adding 3 more arguments to `s3proxy.New()`, which was already very long.

2021-10-30 12:01 UTC, mostynb requested changes
Looks pretty good- I just have a few minor documentation suggestions.

2021-11-01 01:27 UTC, justfalter commented on utils/flags/flags.go
> +			Usage:   "Path to the AWS credentials file. If not specified, the minio client will default to '~/.aws/credentials'. " + s3AuthMsg(s3proxy.AuthMethodAWSCredentialsFile),
I would specify a default value, but Minio actually takes care of locating the home directory on both windows and non-windows systems.

https://github.com/minio/minio-go/blob/master/pkg/credentials/file_aws_credentials.go#L35-L39

2021-11-01 01:49 UTC, justfalter commented on utils/flags/flags.go
> +			Usage:   "Path to the AWS credentials file. If not specified, the minio client will default to '~/.aws/credentials'. " + s3AuthMsg(s3proxy.AuthMethodAWSCredentialsFile),
and https://github.com/minio/minio-go/blob/master/pkg/credentials/file_aws_credentials.go#L63-L70

2021-11-01 21:37 UTC, mostynb approved these changes
This looks good to me- thanks for the submission.

2021-11-01 21:37 UTC, merged

2021-11-02 14:55 UTC, mambon2 commented
Thank you.  I was running into this issue as well.  Would you please update container and documentation on how to pass .aws/credentials to the container?

2021-11-02 20:08 UTC, justfalter commented
@mambon2 Docs added in #493

2021-11-03 22:29 UTC, mambon2 commented
thank you @justfalter